server:
  port: 9000

spring:
  application:
    name: gateway-demo
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        namespace: 7e8c21f2-1384-4b40-809c-aa860e64ac22
        # ??????????
        register-enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # ???????????????????????????
          lower-case-service-id: true
      routes:
        - id: consume-feign # ???ID????????????????????
          uri: lb://consume-feign # ????????????
          predicates:
            - Path=/consume-server/** # ?????????????
          filters:
            - Consumer
            - name: RequestRateLimiter
              args:
                # 用于限流的键的解析器的 Bean 对象的名字
                key-resolver: '#{@ipKeyResolver}'
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 2
                # 令牌桶总容量 能容纳的并发流量总数
                redis-rate-limiter.burstCapacity: 6

# ??????
logging:
  level:
    org.springframework: debug
    com.example.gatewaydemo: debug
