server:
  port: 9000

spring:
  application:
    name: gateway-demo
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        namespace: 7e8c21f2-1384-4b40-809c-aa860e64ac22
        # ??????????
        register-enabled: false
    gateway:
      discovery:
        locator:
          enabled: true # ???????????????????????????
          lower-case-service-id: true
      routes:
        - id: consume-feign # ???ID????????????????????
          uri: lb://consume-feign # ????????????
          predicates:
            - Path=/consume-server/** # ?????????????
          filters:
            - Consumer

# ??????
#logging:
#  level:
#    org.springframework: trace
#    com.example.gatewaydemo: debug

