server:
  port: 9095

spring:
  application:
    name: consume-feign
  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      discovery:
        namespace: 7e8c21f2-1384-4b40-809c-aa860e64ac22
#        不向注册中心注册自己
        register-enabled: false

    loadbalancer:
      retry:
        enabled: true
        retryOnAllOperations: true
        maxRetriesOnNextServiceInstance: 4
        backoff:
          enabled: true       # 重试延迟开启
          min-backoff: 5000   # 最小延迟时间
          max-backoff: 20000  # 最大延迟时间


feign:
  client:
    config:
      default:
        connect-timeout: 5000 #Feign的连接建立超时时间，默认为10秒
        read-timeout: 20000   #Feign的请求处理超时时间，默认为60秒



